SupportInvestigation/Controllers/InvestigationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SupportInvestigation.Models.InterfaceModel;
using SupportInvestigation.Models.Repository;
using SupportInvestigation.Models.Model;
using SupportInvestigation.Models.CustomView;
using PagedList;

namespace SupportInvestigation.Controllers
{
    public class InvestigationController : Controller
    {
         //Intégration du repository
        IRepoHypothesis MsiRepoHypo;
        IRepoUser MsiRepoUser;
        IRepoTicket MsiRepoTicket;
        //Constructor

        public  InvestigationController() : this(new RepoHypothesis(), new RepoUser(), new RepoTicket()){}


        public InvestigationController(IRepoHypothesis repositoryHypo , IRepoUser repositoryUser, IRepoTicket repositoryTicket)
        {
        MsiRepoHypo = repositoryHypo;
        MsiRepoUser = repositoryUser;
            MsiRepoTicket =repositoryTicket;
        }
        //
        // GET: /Investigations/


        //List les investigations en  cours 

        public ViewResult ListHypo(string sortOrder, string searchString, int? page)
        {
            ViewBag.MarchandSortParm = String.IsNullOrEmpty(sortOrder) ? "Name" : "";
            ViewBag.AuteurSortParm = sortOrder == "Auteur" ? "Auteur desc" : "Auteur";
            ViewBag.DateSortParm = sortOrder == "Date" ? "Date desc" : "Date";

            var hypo = MsiRepoHypo.GetAllInvestigationInProgress();
            var hypoSort = hypo.OrderBy(m => m.IDTicket);

            switch (sortOrder)
            {
               
                case "Name":
                    hypoSort = hypo.OrderBy(m => m.IDTicket);
                    break;
                case "Auteur desc":
                    hypoSort = hypo.OrderByDescending(m => m.IDUser);
                    break;
                case "Auteur":
                    hypoSort = hypo.OrderBy(m => m.IDUser);
                    break;
                case "Date desc":
                    hypoSort = hypo.OrderByDescending(m => m.DateCreation);
                    break;
               
                default:
                    hypoSort = hypo.OrderByDescending(i => i.IDTicket);
                    break;

            }


            int pageSize = 10;
            int pageNumber = (page ?? 1);

            //Section Statistique
            var ticket = MsiRepoTicket.GetTicketNoSolved();
            int nbrNoread = 0;
            int nbrRead = 0;
            int nbrSolved = MsiRepoTicket.GetTicketSolved().ToList().Count;
            foreach (var item in ticket)
            {
                if (item.stateRead == 0)
                {
                    nbrNoread++;
                }
                if (item.stateRead == 1)
                {
                    nbrRead++;
                }
            }
            ViewBag.ticketNoRead = nbrNoread;
            ViewBag.ticketRead = nbrRead;
            ViewBag.ticketSolved = nbrSolved;

            return View(hypoSort.ToPagedList(pageNumber, pageSize));
        }

        //Cree une investigation
        public ActionResult Create(int id)
        {       
                Hypothesis investigation = new Hypothesis();
                investigation.IDUser = MsiRepoUser.GetIdByLogin(User.Identity.Name);
            investigation.IDTicket = id;
                return View("Create", investigation);         
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Hypothesis investigation)
        {
            if (investigation != null)
            {
                investigation.StateSolved = 0;
                investigation.DateCreation = DateTime.Now;
                                
                MsiRepoHypo.Add(investigation);
                MsiRepoHypo.Save();

                return View("CreateHypoSuccess");
            }
            return View();
        }

        //Edite une investigation
        public ActionResult Edit(int id)
        {
            return View(MsiRepoHypo.GetInvestigation(id));
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(Hypothesis investigation)
        {

            if (ModelState.IsValid)
            {
                MsiRepoHypo.Update(investigation);
                MsiRepoHypo.Save();
                return View("EditHypoSuccess");
            }
            return View(investigation);
        }


        //voit en détail une investigation
        public ActionResult Details(int id)
        {
            Hypothesis hypothese = MsiRepoHypo.GetInvestigation(id);
            Ticket ticket = MsiRepoTicket.GetTicketBelongToInvestigation(hypothese.IDTicket);
            List<Hypothesis> list = MsiRepoHypo.GestInvestigationByTicket(ticket.TicketID);
            
            InvestigationDetailViewModel detailDuticket = new InvestigationDetailViewModel(hypothese,ticket, list);

            if (ticket == null)
                return View("NotFound");
            else
                return View("Details", detailDuticket);
        }

        //Détruit une investigation
        public ActionResult Delete(int id)
        {
            Hypothesis investigation = MsiRepoHypo.GetInvestigation(id);
            return View(investigation);
        }

        [HttpPost]
        public ActionResult DeleteConfirmed(int id)
        {
            MsiRepoHypo.Delete(MsiRepoHypo.GetInvestigation(id));
            MsiRepoHypo.Save();
            return View("DeleteHypoSuccess");
        }
    }
}

SupportInvestigation/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SupportInvestigation.Models.InterfaceModel;
using SupportInvestigation.Models.Repository;
using SupportInvestigation.Models.Model;
using SupportInvestigation.Models.CustomView;
using System.Collections;
using PagedList;

namespace SupportInvestigation.Controllers
{
    // [OutputCache(Duration=30)] //Mise en cache 30 secondes
    public class TicketController : Controller
    {

        IRepoTicket MsiRepoTicket;
        IRepoUser MsiRepoUser;
        IRepoHypothesis MsiRepoHypo;
        IRepoMarchand MsiRepoMarchand;

        public TicketController() : this(new RepoTicket(), new RepoUser(), new RepoHypothesis(), new RepoMarchand()) { }

        public TicketController(IRepoTicket RepositoryTicket, IRepoUser RepositoryUser, IRepoHypothesis RepositoryHypo, IRepoMarchand RepositoryMarch)
        {
            MsiRepoTicket = RepositoryTicket;
            MsiRepoUser = RepositoryUser;
            MsiRepoHypo = RepositoryHypo;
            MsiRepoMarchand = RepositoryMarch;
        }

        /////////////////////////////////////TICKET///////////////////////////////////////
        //
        // GET: /Ticket/

        public ActionResult Index()
        {
            return View();
        }

        public ViewResult List(string sortOrder, string searchString, int? page)
        {

            ViewBag.MarchandSortParm = String.IsNullOrEmpty(sortOrder) ? "Name desc" : "";
            ViewBag.AuteurSortParm = sortOrder == "Auteur" ? "Auteur desc" : "Auteur";
            ViewBag.DateSortParm = sortOrder == "Date" ? "Date desc" : "Date";
            ViewBag.TitleSortParm = sortOrder == "Title" ? "Title desc" : "Title";
            ViewBag.readSortParm = sortOrder == "Read" ? "Read desc" : "Read";


            var ticket = MsiRepoTicket.GetTicketNoSolved();


            switch (sortOrder)
            {
                case "Name desc":
                    ticket = ticket.OrderByDescending(m => m.Marchands.Url);
                    break;
                case "Name":
                    ticket = ticket.OrderBy(m => m.Marchands.Url);
                    break;
                case "Auteur desc":
                    ticket = ticket.OrderByDescending(m => m.Users.Login);
                    break;
                case "Auteur":
                    ticket = ticket.OrderBy(m => m.Users.Login);
                    break;
                case "Date desc":
                    ticket = ticket.OrderByDescending(m => m.DateCreation);
                    break;
                case "Title desc":
                    ticket = ticket.OrderByDescending(m => m.Title);
                    break;
                case "Title":
                    ticket = ticket.OrderBy(m => m.Title);
                    break;
                case "Read desc":
                    ticket = ticket.OrderByDescending(m => m.stateRead);
                    break;
                case "Read":
                    ticket = ticket.OrderBy(m => m.stateRead);
                    break;
                default:
                    ticket = ticket.OrderByDescending(m => m.DateCreation);
                    break;

            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            // Section Statistique
            int nbrNoread = 0;
            int nbrRead = 0;
            int nbrSolved = MsiRepoTicket.GetTicketSolved().ToList().Count;
            foreach (var item in ticket)
            {
                if (item.stateRead == 0)
                {
                    nbrNoread++;
                }
                if (item.stateRead == 1)
                {
                    nbrRead++;
                }
               
            }
            ViewBag.ticketNoRead = nbrNoread;
            ViewBag.ticketRead = nbrRead;
            ViewBag.ticketSolved = nbrSolved;

            return View(ticket.ToPagedList(pageNumber, pageSize));


        }



        //Voir en détail un ticket
        //GET: /TICKETS/Details/2
        public ActionResult Details(int id)
        {
            Ticket ticket = MsiRepoTicket.GetTicket(id);
            List<Hypothesis> list = MsiRepoHypo.GestInvestigationByTicket(id);
            MsiRepoTicket.UpdateIcketRead(id);
            TicketDetailViewModel detailDuticket = new TicketDetailViewModel(ticket, list);

            if (ticket == null)
                return View("NotFound");
            else
                return View("Details", detailDuticket);
        }


        //Ajouter un ticket
        public ActionResult Add()
        {
            if (User.Identity.IsAuthenticated)
            {
                TicketsAddViewModel ticket = new TicketsAddViewModel();

                ViewData["marchandID"] = marchandBox();
                return View(ticket);
            }
            return RedirectToAction("LogOn", "Profile");
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Add(TicketsAddViewModel customModel)
        {

            if (customModel != null)
            {
                if (customModel.MarchandID == 0)
                {

                    if (customModel.MarchandID == 0 & customModel.Name != null & customModel.Url != null & customModel.Contact != null & customModel.Telephone != 0)
                    {
                        Marchand marchand = new Marchand()
                        {
                            Name = customModel.Name,
                            Url = customModel.Url,
                            Phone = customModel.Telephone,
                            ContactName = customModel.Contact,
                        };
                        MsiRepoMarchand.Add(marchand);
                        MsiRepoMarchand.Save();
                        customModel.MarchandID = MsiRepoMarchand.GetIdMarchand(customModel.Url).MarchandID;

                    }
                    else
                    {

                        ViewData["marchandID"] = marchandBox();
                        if (customModel.MarchandID == 0)
                        {
                            ModelState.AddModelError("choiceError", "Choisissez un marchand dans la liste déroulante ou ajouter un nouveau marchand à l'aide des champs");
                        }

                        if (customModel.Name == null)
                        {

                            ModelState.AddModelError("nameError", "vous devez entrer un nom");
                        }

                        if (customModel.Url == null)
                        {

                            ModelState.AddModelError("urlError", "vous devez entrer une URL");
                        }

                        if (customModel.Telephone == 0)
                        {

                            ModelState.AddModelError("phoneError", "vous devez rentrer un numéro de téléphone");
                        }


                        if (customModel.Contact == null)
                        {

                            ModelState.AddModelError("contactError", "vous devez rentrer le nom de votre contact technique");
                        }


                        return View("Add");
                    }
                }


                //customModel.ID_User = MsiRepoUser.GetUserByMail((User as CustomPrincipal).Mail).UserID;
                customModel.ID_User = MsiRepoUser.GetUser(User.Identity.Name).UserID;
                Ticket ticket = new Ticket()
                {
                    IDUser = customModel.ID_User,
                    Title = customModel.Title,
                    Summary = customModel.Summary,
                    Contents = customModel.Description,
                    DateCreation = DateTime.Now,
                    DateModification = DateTime.Now,
                    StateSolved = 0,
                    stateRead = 0,
                    IDMarchand = customModel.MarchandID
                };
                MsiRepoTicket.Add(ticket);
                MsiRepoTicket.Save();


                return View("CreateTicketSuccess");
            }
            else
                return View("NotFound");
        }

        //Editer un ticket
        public ActionResult Edit(int id)
        {
            return View(MsiRepoTicket.GetTicket(id));
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(Ticket ticket)
        {

            if (ModelState.IsValid)
            {
                MsiRepoTicket.Update(ticket);
                MsiRepoTicket.Save();
                return View("EditTicketSuccess");
            }
            return View(ticket);
        }

        //Effacer un ticket

        public ActionResult Delete(int id)
        {
            Ticket ticket = MsiRepoTicket.GetTicket(id);
            return View(ticket);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            MsiRepoHypo.DeleteHypoBelongToTicket(id);
            MsiRepoTicket.Delete(MsiRepoTicket.GetTicket(id));
            MsiRepoTicket.Save();
            return View("DeleteTicketSuccess");
        }


        //Changer l'état d'un ticket en résolu
        public ActionResult Solved(int id)
        {
            MsiRepoHypo.UpdateHypothesysSolved(id);
            MsiRepoTicket.UpdateTicketSolved(id);
            return View("ArchivedSuccess");
        }


        public List<SelectListItem> marchandBox()
        {

            TicketsAddViewModel ticket = new TicketsAddViewModel();
            ticket.marchands = MsiRepoMarchand.GetAllMarchand();
            var marchanbox = new List<SelectListItem>();
            marchanbox.Add(new SelectListItem { Value = "0", Text = "Please choose" });
            foreach (var item in ticket.marchands)
            {
                marchanbox.Add(new SelectListItem { Value = item.MarchandID.ToString(), Text = item.Url });
            };

SupportInvestigation/Views/Investigation/Create.cshtml
@model SupportInvestigation.Models.Model.Hypothesis
@{
    ViewBag.Title = "Proposer une solution";
}
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@section navBar{
    <form>
    <fieldset>
        <legend>@Html.ActionLink("Retourner sur la liste", "List", "Investigation", new { }, new { @class = "btn btn-large btn-block btn-inverse" })</legend>
    </fieldset>
    </form>
}
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Votre solution</legend>
        <div class="editor-label">
            Titre
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.title)
            @Html.ValidationMessageFor(model => model.title)
        </div>
        <div class="editor-field">
            @Html.HiddenFor(model => model.DateCreation)
            @Html.ValidationMessageFor(model => model.DateCreation)
        </div>
        <div class="editor-field">
            @Html.HiddenFor(model => model.DateModification)
            @Html.ValidationMessageFor(model => model.DateModification)
        </div>
        <div class="editor-field">
            @Html.HiddenFor(model => model.StateSolved)
            @Html.ValidationMessageFor(model => model.StateSolved)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Contents)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Contents, new { @class = "field span12 textarea", @rows = "20" })
            @Html.ValidationMessageFor(model => model.Contents)
        </div>
        <div class="editor-field">
            @Html.HiddenFor(model => model.IDTicket)
            @Html.ValidationMessageFor(model => model.IDTicket)
        </div>
        <div class="editor-field">
            @Html.HiddenFor(model => model.IDUser)
            @Html.ValidationMessageFor(model => model.IDUser)
        </div>
        <p>
            <input type="submit" value="Proposer" name="Name" class="btn" />
        </p>
    </fieldset>
}
<script>
    $('.textarea').wysihtml5({
        "image": false
    });
</script>

SupportInvestigation/Views/Investigation/CreateHypoSuccess.cshtml
@{
    ViewBag.Title = "CreateHypoSuccess";
}

<h2>Votre solution a été envoyé</h2>
@Html.ActionLink("Retour à la liste des propositions", "ListHypo", "Ticket", new { }, new { @class = "btn" })

SupportInvestigation/Views/Investigation/Delete.cshtml
@model SupportInvestigation.Models.Model.Hypothesis

@{
    ViewBag.Title = "Delete";
}

<h2>Alerte Suppression!!!</h2>

<h3>Etes vous sûre de vouloir supprimer cette solution?</h3>
<fieldset>
    <legend>Titre @Html.TextAreaFor(model => model.title, new { @class = "field span12", @rows="1", @maxlength="45", @disabled="disabled"})</legend>

   

    <div class="display-field">
        @Html.HiddenFor(model => model.DateCreation)
    </div>

    <div class="display-field">
        @Html.HiddenFor(model => model.DateModification)
    </div>

    <div class="display-field">
        @Html.HiddenFor(model => model.StateSolved)
    </div>
    <div class="editor-field">
            @Html.TextAreaFor(model => model.Contents, new { @class = "field span12", @rows = "20", @disabled = "disabled" })

    

    <div class="display-field">
        @Html.HiddenFor(model => model.IDTicket)
    </div>

    <div class="display-field">
        @Html.HiddenFor(model => model.IDUser)
    </div>
</fieldset>
@using (Html.BeginForm())
{
    <p>
        <input type="submit" value="Effacer"  class="btn btn-large btn-danger" /> |
        @Html.ActionLink("Retourner sur la liste", "ListHypo", new { }, new { @class = "btn btn-large btn-inverse" })
    </p>
}

SupportInvestigation/Views/Investigation/DeleteHypoSuccess.cshtml
@{
    ViewBag.Title = "DeleteTicketSuccess";
}

<h2>Votre Hypothese à bien été supprimé</h2>
 @Html.ActionLink("Retour à la liste", "ListHypo", new { }, new { @class = "btn" })

SupportInvestigation/Views/Investigation/Details.cshtml
@model SupportInvestigation.Models.CustomView.InvestigationDetailViewModel
@{
    ViewBag.Title = "Details";
}
@section navBar{
    <h5>
    </h5>
    <br />
    @if (User.Mail == Model.hypothese.Users.Mail)
    {
        @Html.ActionLink("Modifier votre solution", "Edit", new { id = Model.hypothese.hypothesisID }, new { @class = "btn btn-large btn-block btn-info" })
        @Html.ActionLink("Effacer", "Delete", new { id = Model.hypothese.hypothesisID }, new { @class = "btn btn-large btn-block btn-warning" })    
    }
    else
    {<button class="btn btn-large btn-block btn-info disabled">Modifier votre solution</button>
      <button class="btn btn-large btn-block btn-warning disabled">Effacer</button>
    }
    @Html.ActionLink("Proposer une solution", "Create", "Investigation", new { id = Model.Ticket.TicketID }, new { @class = "myclass btn btn-large btn-block btn-primary" })
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <button class="btn btn-large btn-block" type="button">
        @Html.ActionLink("Retourner à la liste", "ListHypo", "Investigation")</button>
    <br />
    <br />
    <br />
}
<h3>
    Le ticket à résoudre</h3>
<fieldset>
    <legend><small>@Html.DisplayFor(model => model.Ticket.Title)</small></legend>
    @Html.TextAreaFor(model => model.Ticket.Contents, new { @class = "field span12 textarea", @rows = "20" })
    <div class="pull-left">@Model.Ticket.DateCreation.ToShortDateString()</div>
    <div class="pull-right">
        <strong>Auteur : </strong><em>@Html.DisplayFor(model => model.Ticket.Users.Login)</em></div>
</fieldset>
<h3>
    Votre solution</h3>
<fieldset>
    <legend>@Html.DisplayFor(model => model.hypothese.title)</legend>
    @Html.TextAreaFor(model => model.hypothese.Contents, new { @class = "field span12 textarea", @rows = "20" })
    <div class="pull-left">@Model.hypothese.DateCreation.ToShortDateString()</div>
    <div class="pull-right">
        <strong>Auteur : </strong><em>@Html.DisplayFor(model => model.hypothese.Users.Login)</em></div>
</fieldset>
<br />
<h2 class="pagination-centered">
    Historique des Solutions</h2>
@foreach (var item in Model.Investigation)
{
    <form>
    <fieldset>
        <legend>@item.title</legend>
        <textarea class="field span12 textarea" rows="20">@item.Contents</textarea>
    </fieldset>
    </form>
    <hr />
    <div class="pull-left">
        Crée le : @item.DateCreation.ToShortDateString()</div>
    <div class="pull-right">
        <strong>Auteur : </strong><em>@item.Users.Login</em></div>
    
    <br />   
    <br />
}
@Html.ActionLink("Proposer une solution", "Create", "Investigation", new { id = Model.Ticket.TicketID }, new { @class = "myclass btn btn-large btn-block btn-primary" })
<script>
    $('.textarea').wysihtml5(

    { "font-styles": false,
        "emphasis": false,
        "lists": false,
        "html": false,
        "link": false,
        "image": false,
        "color": false
    }
    );
</script>

SupportInvestigation/Views/Investigation/Edit.cshtml
@model SupportInvestigation.Models.Model.Hypothesis
@{
    ViewBag.Title = "Edit";
}
@section navBar{
    <h5>
    </h5>
    <br />
    @Html.ActionLink("Archiver", "Solved", new { }, new { @class = "btn btn-large btn-block btn-success" })
    <br />
    <br />
    <br />
    @Html.ActionLink("Effacer", "Delete", new { }, new { @class = "btn btn-large btn-block btn-warning" })
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <button class="btn btn-large btn-block" type="button">
        @Html.ActionLink("Retourner à la liste", "ListHypo", "Investigation")</button>
    <br />
    <br />
    <br />
}
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Titre @Html.EditorFor(model => model.title)</legend>@Html.ValidationMessageFor(model => model.title)
        @Html.HiddenFor(model => model.hypothesisID)
        <div class="editor-field">
            @Html.HiddenFor(model => model.DateCreation)
        </div>
        <div class="editor-field">
            @Html.HiddenFor(model => model.DateModification)
        </div>
        <div class="editor-field">
            @Html.HiddenFor(model => model.StateSolved)
            @Html.ValidationMessageFor(model => model.StateSolved)
        </div>
        <div class="editor-label">
            Formulaire
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Contents, new { @class = "field span12 textarea", @rows = "20" })
            @Html.ValidationMessageFor(model => model.Contents)
        </div>
        <div class="editor-field">
            @Html.HiddenFor(model => model.IDTicket)
        </div>
        <div class="pull-left">
            <strong>Crée le : </strong><em>@Model.DateCreation.ToShortDateString() </em>
        </div>
        <div class="pull-right">
            <strong>Auteur</strong>
            @Html.HiddenFor(model => model.IDUser)
            @Html.DisplayFor(model => model.Users.Login)
            @Html.ValidationMessageFor(model => model.IDUser)
        </div>
        <br />
        <br />
        <input type="submit" value="Save" class="btn btn-large" />
    </fieldset>
}
<script>
    $('.textarea').wysihtml5({
        "image": false
    });
</script>

SupportInvestigation/Views/Investigation/EditHypoSuccess.cshtml
@{
    ViewBag.Title = "EditHypoSuccess";
}

<h2>Votre hypothese à bien été modifié</h2>
@Html.ActionLink("Retour à la liste des tickets", "List", "Ticket", new { }, new { @class = "btn" })

SupportInvestigation/Views/Investigation/ListHypo.cshtml
@model PagedList.IPagedList<SupportInvestigation.Models.Model.Hypothesis>
<script type="text/javascript">    $("li.lien2").addClass(" active")</script>
@{
    ViewBag.Title = "Investigations en cours";
}
@section navBar{
    <form>
    <fieldset>
        <legend>Trier par:</legend>
        @Html.ActionLink("Par ticket", "ListHypo", new { sortOrder = ViewBag.MarchandSortParm }, new { @class = "btn btn-large btn-block btn-info" })
        @Html.ActionLink("Auteur", "ListHypo", new { sortOrder = ViewBag.AuteurSortParm }, new { @class = "btn btn-large btn-block btn-info" })
        @Html.ActionLink("Date", "ListHypo", new { sortOrder = ViewBag.DateSortParm }, new { @class = "btn btn-large btn-block btn-info" })
    </fieldset>
    <hr />
    <fieldset>
        <legend>Navigation</legend>
        <div style="text-align: center">
            @if (Model.HasPreviousPage)
            {          
                <a href="@Url.Action("ListHypo", new { page = 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })">
                    <i class="icon-fast-backward"></i></a>
                @Html.Raw(" ");
        
                <a href="@Url.Action("ListHypo", new { page = Model.PageNumber - 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })">
                    <i class="icon-backward"></i>Precedent</a>                      
            }
            else
            {
                @:<i class=" icon-ban-circle"></i>
        @Html.Raw(" ");
                @:<i class=" icon-chevron-left"></i> Precedent
                }
            @if (Model.HasNextPage)
            {
                <a href="@Url.Action("ListHypo", new { page = Model.PageNumber + 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })">
                    Suivant <i class="icon-forward"></i></a>             
                @Html.Raw(" ");
                      
                <a href="@Url.Action("ListHypo", new { page = Model.PageCount, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })">
                    <i class="icon-fast-forward"></i></a>                          
            }
            else
            {
                @:Suivant <i class="icon-chevron-right"></i>
        @Html.Raw(" ")
                @:<i class="icon-ban-circle"></i>
                }
            <br />
            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
            sur @Model.PageCount
        </div>
    </fieldset>
    <fieldset>
    <legend>Statistiques:</legend>

    Nombre D'investigations en cours @Model.TotalItemCount
    <br />
    Nombre de tickets non lus :@ViewBag.ticketNoRead
    <br />
    Nombre de ticket en cours de résolution :@ViewBag.ticketRead
    <br />
    Nombre de ticket résolus :@ViewBag.ticketSolved
    </fieldset>
    </form>
}
<fieldset>
    <legend>Dernières investigations</legend>
    <table class="table">
        <tr>
            <th>
                iD
            </th>
            <th>
                <i class="icon-calendar"></i>Date
            </th>
            <th>
                N°
            </th>
            <th>
                Nom du ticket
            </th>
            <th>
                <i class="icon-file"></i>Solution
            </th>
            <th>
               <i class="icon-user"></i>
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.hypothesisID)
                </td>
                <td>
                    @item.DateCreation.ToShortDateString()
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IDTicket)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tickets.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Users.Login)
                </td>
                <td>
                    @Html.ActionLink("Lire", "Details", new { id = item.hypothesisID }, new { @class = "btn btn-small" })
                </td>
            </tr>
        }
    </table>
</fieldset>