SupportInvestigation/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SupportInvestigation.Models.InterfaceModel;
using SupportInvestigation.Models.Repository;
using SupportInvestigation.Models.Model;
using SupportInvestigation.Models.CustomView;
using System.Collections;
using PagedList;

namespace SupportInvestigation.Controllers
{
    // [OutputCache(Duration=30)] //Mise en cache 30 secondes
    public class TicketController : Controller
    {

        IRepoTicket MsiRepoTicket;
        IRepoUser MsiRepoUser;
        IRepoHypothesis MsiRepoHypo;
        IRepoMarchand MsiRepoMarchand;

        public TicketController() : this(new RepoTicket(), new RepoUser(), new RepoHypothesis(), new RepoMarchand()) { }

        public TicketController(IRepoTicket RepositoryTicket, IRepoUser RepositoryUser, IRepoHypothesis RepositoryHypo, IRepoMarchand RepositoryMarch)
        {
            MsiRepoTicket = RepositoryTicket;
            MsiRepoUser = RepositoryUser;
            MsiRepoHypo = RepositoryHypo;
            MsiRepoMarchand = RepositoryMarch;
        }

        /////////////////////////////////////TICKET///////////////////////////////////////
        //
        // GET: /Ticket/

        public ActionResult Index()
        {
            return View();
        }

        public ViewResult List(string sortOrder, string searchString, int? page)
        {

            ViewBag.MarchandSortParm = String.IsNullOrEmpty(sortOrder) ? "Name desc" : "";
            ViewBag.AuteurSortParm = sortOrder == "Auteur" ? "Auteur desc" : "Auteur";
            ViewBag.DateSortParm = sortOrder == "Date" ? "Date desc" : "Date";
            ViewBag.TitleSortParm = sortOrder == "Title" ? "Title desc" : "Title";
            ViewBag.readSortParm = sortOrder == "Read" ? "Read desc" : "Read";


            var ticket = MsiRepoTicket.GetTicketNoSolved();


            switch (sortOrder)
            {
                case "Name desc":
                    ticket = ticket.OrderByDescending(m => m.Marchands.Url);
                    break;
                case "Name":
                    ticket = ticket.OrderBy(m => m.Marchands.Url);
                    break;
                case "Auteur desc":
                    ticket = ticket.OrderByDescending(m => m.Users.Login);
                    break;
                case "Auteur":
                    ticket = ticket.OrderBy(m => m.Users.Login);
                    break;
                case "Date desc":
                    ticket = ticket.OrderByDescending(m => m.DateCreation);
                    break;
                case "Title desc":
                    ticket = ticket.OrderByDescending(m => m.Title);
                    break;
                case "Title":
                    ticket = ticket.OrderBy(m => m.Title);
                    break;
                case "Read desc":
                    ticket = ticket.OrderByDescending(m => m.stateRead);
                    break;
                case "Read":
                    ticket = ticket.OrderBy(m => m.stateRead);
                    break;
                default:
                    ticket = ticket.OrderByDescending(m => m.DateCreation);
                    break;

            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            // Section Statistique
            int nbrNoread = 0;
            int nbrRead = 0;
            int nbrSolved = MsiRepoTicket.GetTicketSolved().ToList().Count;
            foreach (var item in ticket)
            {
                if (item.stateRead == 0)
                {
                    nbrNoread++;
                }
                if (item.stateRead == 1)
                {
                    nbrRead++;
                }
               
            }
            ViewBag.ticketNoRead = nbrNoread;
            ViewBag.ticketRead = nbrRead;
            ViewBag.ticketSolved = nbrSolved;

            return View(ticket.ToPagedList(pageNumber, pageSize));


        }



        //Voir en détail un ticket
        //GET: /TICKETS/Details/2
        public ActionResult Details(int id)
        {
            Ticket ticket = MsiRepoTicket.GetTicket(id);
            List<Hypothesis> list = MsiRepoHypo.GestInvestigationByTicket(id);
            MsiRepoTicket.UpdateIcketRead(id);
            TicketDetailViewModel detailDuticket = new TicketDetailViewModel(ticket, list);

            if (ticket == null)
                return View("NotFound");
            else
                return View("Details", detailDuticket);
        }


        //Ajouter un ticket
        public ActionResult Add()
        {
            if (User.Identity.IsAuthenticated)
            {
                TicketsAddViewModel ticket = new TicketsAddViewModel();

                ViewData["marchandID"] = marchandBox();
                return View(ticket);
            }
            return RedirectToAction("LogOn", "Profile");
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Add(TicketsAddViewModel customModel)
        {

            if (customModel != null)
            {
                if (customModel.MarchandID == 0)
                {

                    if (customModel.MarchandID == 0 & customModel.Name != null & customModel.Url != null & customModel.Contact != null & customModel.Telephone != 0)
                    {
                        Marchand marchand = new Marchand()
                        {
                            Name = customModel.Name,
                            Url = customModel.Url,
                            Phone = customModel.Telephone,
                            ContactName = customModel.Contact,
                        };
                        MsiRepoMarchand.Add(marchand);
                        MsiRepoMarchand.Save();
                        customModel.MarchandID = MsiRepoMarchand.GetIdMarchand(customModel.Url).MarchandID;

                    }
                    else
                    {

                        ViewData["marchandID"] = marchandBox();
                        if (customModel.MarchandID == 0)
                        {
                            ModelState.AddModelError("choiceError", "Choisissez un marchand dans la liste déroulante ou ajouter un nouveau marchand à l'aide des champs");
                        }

                        if (customModel.Name == null)
                        {

                            ModelState.AddModelError("nameError", "vous devez entrer un nom");
                        }

                        if (customModel.Url == null)
                        {

                            ModelState.AddModelError("urlError", "vous devez entrer une URL");
                        }

                        if (customModel.Telephone == 0)
                        {

                            ModelState.AddModelError("phoneError", "vous devez rentrer un numéro de téléphone");
                        }


                        if (customModel.Contact == null)
                        {

                            ModelState.AddModelError("contactError", "vous devez rentrer le nom de votre contact technique");
                        }


                        return View("Add");
                    }
                }


                //customModel.ID_User = MsiRepoUser.GetUserByMail((User as CustomPrincipal).Mail).UserID;
                customModel.ID_User = MsiRepoUser.GetUser(User.Identity.Name).UserID;
                Ticket ticket = new Ticket()
                {
                    IDUser = customModel.ID_User,
                    Title = customModel.Title,
                    Summary = customModel.Summary,
                    Contents = customModel.Description,
                    DateCreation = DateTime.Now,
                    DateModification = DateTime.Now,
                    StateSolved = 0,
                    stateRead = 0,
                    IDMarchand = customModel.MarchandID
                };
                MsiRepoTicket.Add(ticket);
                MsiRepoTicket.Save();


                return View("CreateTicketSuccess");
            }
            else
                return View("NotFound");
        }

        //Editer un ticket
        public ActionResult Edit(int id)
        {
            return View(MsiRepoTicket.GetTicket(id));
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(Ticket ticket)
        {

            if (ModelState.IsValid)
            {
                MsiRepoTicket.Update(ticket);
                MsiRepoTicket.Save();
                return View("EditTicketSuccess");
            }
            return View(ticket);
        }

        //Effacer un ticket

        public ActionResult Delete(int id)
        {
            Ticket ticket = MsiRepoTicket.GetTicket(id);
            return View(ticket);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            MsiRepoHypo.DeleteHypoBelongToTicket(id);
            MsiRepoTicket.Delete(MsiRepoTicket.GetTicket(id));
            MsiRepoTicket.Save();
            return View("DeleteTicketSuccess");
        }


        //Changer l'état d'un ticket en résolu
        public ActionResult Solved(int id)
        {
            MsiRepoHypo.UpdateHypothesysSolved(id);
            MsiRepoTicket.UpdateTicketSolved(id);
            return View("ArchivedSuccess");
        }


        public List<SelectListItem> marchandBox()
        {

            TicketsAddViewModel ticket = new TicketsAddViewModel();
            ticket.marchands = MsiRepoMarchand.GetAllMarchand();
            var marchanbox = new List<SelectListItem>();
            marchanbox.Add(new SelectListItem { Value = "0", Text = "Please choose" });
            foreach (var item in ticket.marchands)
            {
                marchanbox.Add(new SelectListItem { Value = item.MarchandID.ToString(), Text = item.Url });
            };

SupportInvestigation/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using SupportInvestigation.Models.InterfaceModel;
using SupportInvestigation.Models.Repository;
using SupportInvestigation.Models.Administration;
using SupportInvestigation.Models.Model;
using SupportInvestigation.Helpers;
using System.Security.Cryptography;
using System.Web.Script.Serialization;

namespace SupportInvestigation.Controllers
{
    public class UserController : BaseController 
    {
       //
        // GET: /Profile/
        IRepoUser MsiRepoUser;
       // int levelAdmin = 0;
       // int levelUser = 1;
        string roleUser = "";

        public string CookieName { get; set; }
        
        public UserController() : this(new RepoUser()) { }

        public UserController(IRepoUser Repository) {
            MsiRepoUser = Repository;
        }

        //Connecte un utilisateur
        public ActionResult LogOn()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LogOn(AccountUser model)
        {           
            if (ModelState.IsValid)
            {
                                
                // Initialize FormsAuthentification for web.config
                FormsAuthentication.Initialize();

               // Hash du mot de passe
                 MD5 md5Hash = MD5.Create();

                string hashPass = MD5Hash.GetMd5Hash(md5Hash, model.Password);

                MD5Hash.VerifyMd5Hash(md5Hash, model.Password, hashPass);
                
                User logUser = MsiRepoUser.GetLoginAndPass(model.Login, hashPass);

                if (logUser != null)
                {
                    if (logUser.Level == 0)
                    {
                        roleUser = "Admins";
                    }
                    else
                    {
                        roleUser = "Users";
                    }

                    
                    HttpCookie cookieId = new HttpCookie("Mycookie");
                    cookieId["UserId"] = logUser.UserID.ToString();



                    SerializeModel serializeModel = new SerializeModel();
                    serializeModel.UserId = logUser.UserID;
                    serializeModel.Mail = logUser.Mail;
                    serializeModel.LastName = logUser.Login;
                    serializeModel.Role = roleUser;


                    JavaScriptSerializer serializer = new JavaScriptSerializer();

                    string userData = serializer.Serialize(serializeModel);

                    //Create a new ticket used for authentification
                    FormsAuthenticationTicket ticket = new FormsAuthenticationTicket(
                        1, //Ticket version
                        model.Login, //Username associed with ticket
                        DateTime.Now, //Date/time issued
                        DateTime.Now.AddMinutes(30), //DateTime to expire
                        true,//Persistent cookie
                        userData,//roleUser,//role
                        FormsAuthentication.FormsCookiePath);


                    //Encrypt the Cookie using the machine key for secure transport
                    string hash = FormsAuthentication.Encrypt(ticket);
                    HttpCookie cookie = new HttpCookie(FormsAuthentication.FormsCookieName, hash);

                    if (ticket.IsPersistent) cookie.Expires = ticket.Expiration;

                    //Add the cookie to the list for outgoing response
                    Response.Cookies.Add(cookie);

                    //Redirect to requested URL, or Homepage if no previous page requested
                    string returnUrl = Request.QueryString[""];
                    if (returnUrl == null) returnUrl = "/Ticket/list";

                    Response.Redirect(returnUrl);
                }
                else
                {
                    ModelState.AddModelError("", "Mot de passe ou login invalide");
                }

            }
           
            return View();
        }

        public ActionResult Home()
        {

            return View();
        }

        //Déconnecte un utilisateur
        public ActionResult LogOff()
        {
            
            FormsAuthentication.SignOut();

            return RedirectToAction("Index", "Home");
        }
                
    }

    
}

SupportInvestigation/Views/Shared/_Layout.cshtml
@inherits SupportInvestigation.Models.CustomView.BaseViewPage
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/bootstrap/editor/bootstrap-wysihtml5.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap/css/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Content/bootstrap/editor/wysihtml5-0.3.0.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/bootstrap/js/jquery-1.8.0.min.js")" type="text/javascript"></script> 
    <script src="@Url.Content("~/Content/bootstrap/js/bootstrap.min.js")"></script>
     <script src="@Url.Content("~/Content/bootstrap/editor/bootstrap-wysihtml5.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
   
   
    

    <style type="text/css">
    .content
    {
      min-height: 450px;  
    }
    .BodyContent
    {
      min-height: 200px;
    }
    .BodyHypoContent
    {
      min-height: 200px; 
    }
    </style>
</head>
<body>
    <header>
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container">
                    <a class="brand" href="#">Marchand Support investigation</a>
                    <ul class="nav">
                       <li><a href="@Url.Action("List","Ticket")"><i class="icon-home"></i> Accueil</a></li>
                                          
                        @if(User.IsInRole("Admins"))
                        {
                           <li><a href="@Url.Action("Home","Administration")"><i class="icon-wrench"></i>  Administration</a></li>
                        }
                        else
                        {
                        <li><a href="@Url.Action("Home","User")"><i class="icon-map-marker"></i> Mon Espace</a></li>
                        }

                       
        
                       
                    </ul>
                    <ul class="nav pull-right">
                        @Html.Partial("_LogOnPartial")
                    </ul>
                </div>
            </div>
        </div>
    </header>
    
        <div class="container-fluid">
        <ul class="nav nav-tabs">
        
        <li class="lien1">@Html.ActionLink("Tickets", "List", "Ticket")</li>
         <li class="lien2">@Html.ActionLink("Investigations", "ListHypo", "Investigation")</li>
         <li class="lien3">@Html.ActionLink("Archives", "Archived", "Ticket")</li>
       @Html.ActionLink("Créer un ticket", "Add", "Ticket", new { }, new { @class = "btn btn-primary pull-right" })
        </ul>
        
        <div class=content>
            <div class="row-fluid">
                <div class="span8">
                    
                    @RenderBody()
                    
                </div>
                <div class="span4">
               
                    <div>@RenderSection("navBar",false)</div>
                
                </div>
            </div>
            </div>
        </div>
    <footer>
    </footer>
    <br />
    <hr />
    <footer>
        <p style="text-align:center">
            &copy; Un projet de <a href="mailto:jeanchristophedemar@yahoo.fr?Subject=Msi%Contact">Jc Demar</a>- 2012</p>
    </footer>
   
</body>
</html>

SupportInvestigation/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "User") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "User") ]
}

SupportInvestigation/Views/Shared/_Menu.cshtml
Affichache du menu 
<ul>
    <li>@Html.ActionLink("Liste des investigation","ListHypo","Investigation")</li>
    <li>deux</li>
</ul>